name: CI/CD Pipeline for Ubuntu App

on:
  push:
    branches:
      - main 

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t clownprince/ubuntu-app:latest .

      - name: Run Unit Test (Container Health Check)
        run: |
          container_id=$(docker run -d -p 8080:80 clownprince/ubuntu-app:latest)
          sleep 5
          curl -s http://localhost:8080 | grep "Hello from my Ubuntu-based App"
          docker stop $container_id

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clownprince/ubuntu-app:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push clownprince/ubuntu-app:latest
